@echo off
echo Starting Student Search Web App...
echo Installing Flask if not installed...
.\venv\Scripts\pip install Flask
echo Starting server...
start http://127.0.0.1:5001
.\venv\Scripts\python.exe app.py
pause
